import { defineConfig, presetIcons, presetUno } from 'unocss'

export default defineConfig({
  presets: [
    presetUno(),
    presetIcons({
      scale: 1.2,
      cdn: 'https://esm.sh/',
      extraProperties: {
        display: 'inline-block',
        'vertical-align': 'middle',
      },
    }),
  ],
  theme: {
    colors: {
      'nais-bg': '#FFFFFF',
      'nais-surface': '#F1F5F9',
      'nais-card': '#F8FAFC',
      'nais-text': '#0F172A',
      'nais-text-secondary': '#64748B',
      'nais-accent': '#E8384F',
      'nais-accent-hover': '#DC2626',
      'nais-accent-light': '#FEF2F2',
      'nais-border': '#E2E8F0',
      'nais-success': '#10B981',
    },
  },
  safelist: [
    'i-carbon-terminal',
    'i-carbon-favorite-filled',
    'i-carbon-book',
    'i-carbon-logo-linkedin',
    'i-carbon-play-filled',
    'i-carbon-badge',
    'i-carbon-wifi',
    'i-carbon-microphone',
    'i-carbon-cafe',
    'i-carbon-restaurant',
    'i-carbon-music',
    'i-carbon-gift',
    'i-carbon-star-filled',
    'i-carbon-checkmark-filled',
    'i-carbon-arrow-right',
    'i-carbon-email',
    'i-carbon-globe',
    'i-carbon-user-multiple',
    'i-carbon-calendar',
    'i-carbon-location',
    'i-carbon-money',
    'i-carbon-partnership',
    'i-carbon-presentation-file',
    'i-carbon-megaphone',
    'i-carbon-code',
    'i-carbon-group',
    'i-carbon-chat',
    'i-carbon-document',
    'i-carbon-task',
    'i-carbon-video',
    'i-carbon-ticket',
    'i-carbon-calculator',
    'i-carbon-rocket',
    'i-carbon-growth',
    'i-carbon-enterprise',
    'i-carbon-warning',
    'i-carbon-help',
    'i-carbon-hashtag',
    'i-carbon-logo-github',
    'i-carbon-bullhorn',
  ],
})
