import { defineConfig, presetIcons, presetUno } from 'unocss'

export default defineConfig({
  presets: [
    presetUno(),
    presetIcons({
      scale: 1.2,
      cdn: 'https://esm.sh/',
      extraProperties: {
        display: 'inline-block',
        'vertical-align': 'middle',
      },
    }),
  ],
  theme: {
    colors: {
      'nais-bg': '#0a0a0a',
      'nais-surface': '#141414',
      'nais-card': '#1a1a1a',
      'nais-text': '#e5e5e5',
      'nais-text-secondary': '#737373',
      'nais-accent': '#e8384f',
      'nais-accent-hover': '#ff4d63',
      'nais-accent-light': 'rgba(232, 56, 79, 0.12)',
      'nais-border': '#262626',
      'nais-success': '#22c55e',
    },
  },
  safelist: [
    'i-carbon-terminal',
    'i-carbon-checkmark-filled',
    'i-carbon-arrow-right',
    'i-carbon-globe',
    'i-carbon-user-multiple',
    'i-carbon-money',
    'i-carbon-code',
    'i-carbon-group',
    'i-carbon-chat',
    'i-carbon-rocket',
    'i-carbon-growth',
    'i-carbon-help',
    'i-carbon-logo-github',
    'i-carbon-data-base',
    'i-carbon-container-services',
    'i-carbon-locked',
    'i-carbon-kubernetes',
    'i-carbon-network-3',
    'i-carbon-dashboard',
    'i-carbon-analytics',
    'i-carbon-currency',
    'i-carbon-settings-adjust',
    'i-carbon-upgrade',
    'i-carbon-chevron-right',
    'i-carbon-unlocked',
    'i-carbon-user-flow',
    'i-carbon-piggy-bank',
    'i-carbon-gui',
    'i-carbon-chart-line',
    'i-carbon-server-proxy',
    'i-carbon-cloud-monitoring',
    'i-carbon-security',
    'i-carbon-application',
    'i-carbon-task',
    'i-carbon-warning-hex',
    'i-carbon-idea',
    'i-carbon-lightbulb-filled',
    'i-carbon-share-knowledge',
    'i-carbon-target',
    'i-carbon-collaborate',
    'i-carbon-roadmap',
    'i-carbon-chart-bar',
    'i-carbon-meter',
    'i-carbon-search',
    'i-carbon-clean',
  ],
})
